logging:
  level:
    ROOT: INFO
    io.ktor.client: ERROR
    org.telegram.telegrambots: DEBUG
    org.springframework.web.client: DEBUG
    # org.apache.http: DEBUG
    # httpclient.wire: DEBUG

bot:
  username: motorsportsdb_bot
  token: ${telegram_token}

server.port: 8998

spring:
  messages:
    basename: i18n.messages
    defaultLocale: en
    fallback-to-system-locale: true
    encoding: UTF-8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/msdb?useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: msdb
    password: msdb
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: msdb