bot:
  username: motorsportsdb_bot

app:
  # server: https://www.motorsports-database.racing
  server: http://localhost:8080

spring:
  datasource:
    password: msdb07pwd@
    hikari:
      poolName: Hikari
      auto-commit: false
      max-lifetime: 600000 # 10 minutes

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true